# Generated by Django 4.1.7 on 2023-03-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='lession_type',
            new_name='lesson_type',
        ),
    ]
